version: '2'
services:
  nginx:
    image: evild/alpine-nginx:1.9.15-openssl
    container_name: lemop_nginx
    links:
      - php
    volumes:
      - ~/Phpworkspace:/var/www/html/:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
      - 443:443
  php:
    image: hayko18/php7-mongo
    container_name: lemop_php
    volumes:
      - ~/Phpworkspace:/var/www/html
    depends_on:
      - db
    links:
      - db
  db:
    image: mongo:latest
    container_name: lemop_mongodb
    volumes:
      - /data/db
